In [184]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

In [387]:
path = '/Users/jimmychu/Downloads/Lab_2/assignment1a.csv'

df = pd.read_csv(path,
     usecols=[1, 2, 3, 4, 5, 6])


df.head()


Age       Sex  Monthly Income  Marital status  Service plan  Extra useage
0    54  FEMALE              3000           YES            100             0
1    59  FEMALE              4000            NO            600            54
2    38    MALE              7800            NO            200            31
3    18  FEMALE              8500            NO            600           311
4    27    MALE             14000           YES            100           211

In [388]:
# Change categorical data to number 0-2
df["Marital status"] = pd.Categorical(df["Marital status"])
df["Marital status"] = df["Marital status"].cat.codes
df["Sex"] = pd.Categorical(df["Sex"])
df["Sex"] = df["Sex"].cat.codes
df

Age   Sex  Monthly Income   Marital status  Service plan  Extra useage
0     54    0             3000               1           100             0
1     59    0             4000               0           600            54
2     38    1             7800               0           200            31
3     18    0             8500               0           600           311
4     27    1            14000               1           100           211
5     29    0            31000               1          1600            25
6     17    1             7500               0           600           254
7     22    0             7900               0           200            31
8     34    1            24700               0           100             7
9     46    0            31110               1           600             0
10    39    0            21000               1           800            64
11    35    0            30000               0          1600             0
12    39    1            40500               1          1600            50
13    18    1             7800               0          1000           290
14    22    1            18000               1           400           303

In [389]:
x = df.values[:, 0:6]
x



array([[   54,     0,  3000,     1,   100,     0],
       [   59,     0,  4000,     0,   600,    54],
       [   38,     1,  7800,     0,   200,    31],
       [   18,     0,  8500,     0,   600,   311],
       [   27,     1, 14000,     1,   100,   211],
       [   29,     0, 31000,     1,  1600,    25],
       [   17,     1,  7500,     0,   600,   254],
       [   22,     0,  7900,     0,   200,    31],
       [   34,     1, 24700,     0,   100,     7],
       [   46,     0, 31110,     1,   600,     0],
       [   39,     0, 21000,     1,   800,    64],
       [   35,     0, 30000,     0,  1600,     0],
       [   39,     1, 40500,     1,  1600,    50],
       [   18,     1,  7800,     0,  1000,   290],
       [   22,     1, 18000,     1,   400,   303]])

In [402]:
X_scaled = preprocessing.scale(x)


/Users/jimmychu/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)


In [417]:
X_scaled    

array([[ 1.65388686, -0.93541435, -1.22873488,  1.06904497, -1.07973422,
        -0.90520859],
       [ 2.05018563, -0.93541435, -1.14171811, -0.93541435, -0.13810554,
        -0.45565681],
       [ 0.3857308 ,  1.06904497, -0.81105436, -0.93541435, -0.89140848,
        -0.64713256],
       [-1.19946427, -0.93541435, -0.75014262, -0.93541435, -0.13810554,
         1.68387667],
       [-0.48612649,  1.06904497, -0.27155035,  1.06904497, -1.07973422,
         0.85137337],
       [-0.32760698, -0.93541435,  1.20773484,  1.06904497,  1.74515181,
        -0.69708276],
       [-1.27872403,  1.06904497, -0.83715939, -0.93541435, -0.13810554,
         1.20934979],
       [-0.88242526, -0.93541435, -0.80235268, -0.93541435, -0.89140848,
        -0.64713256],
       [ 0.06869179,  1.06904497,  0.65952915, -0.93541435, -1.07973422,
        -0.84693336],
       [ 1.01980883, -0.93541435,  1.21730668,  1.06904497, -0.13810554,
        -0.90520859],
       [ 0.46499055, -0.93541435,  0.33756708,  1.

In [418]:
#scaler = preprocessing.StandardScaler().fit(x)

In [419]:
#scaler

In [420]:
#scaler.mean_

In [421]:
#scaler.transform(x)   

In [422]:
min_max_scaler = preprocessing.MinMaxScaler()
X_scaled_minmax = min_max_scaler.fit_transform(X_scaled)

In [423]:
X_scaled_minmax 

array([[0.88095238, 0.        , 0.        , 1.        , 0.        ,
        0.        ],
       [1.        , 0.        , 0.02666667, 0.        , 0.33333333,
        0.17363344],
       [0.5       , 1.        , 0.128     , 0.        , 0.06666667,
        0.09967846],
       [0.02380952, 0.        , 0.14666667, 0.        , 0.33333333,
        1.        ],
       [0.23809524, 1.        , 0.29333333, 1.        , 0.        ,
        0.67845659],
       [0.28571429, 0.        , 0.74666667, 1.        , 1.        ,
        0.08038585],
       [0.        , 1.        , 0.12      , 0.        , 0.33333333,
        0.81672026],
       [0.11904762, 0.        , 0.13066667, 0.        , 0.06666667,
        0.09967846],
       [0.4047619 , 1.        , 0.57866667, 0.        , 0.        ,
        0.02250804],
       [0.69047619, 0.        , 0.7496    , 1.        , 0.33333333,
        0.        ],
       [0.52380952, 0.        , 0.48      , 1.        , 0.46666667,
        0.20578778],
       [0.42857143, 0

In [424]:
C1=X_scaled_minmax[0]
C2=X_scaled_minmax[7]
C3=X_scaled_minmax[14]
X = np.vstack((C1,C2,C3))
X

array([[0.88095238, 0.        , 0.        , 1.        , 0.        ,
        0.        ],
       [0.11904762, 0.        , 0.13066667, 0.        , 0.06666667,
        0.09967846],
       [0.11904762, 1.        , 0.4       , 1.        , 0.2       ,
        0.97427653]])

In [425]:
km = KMeans(n_clusters=3, init=X, n_init=1)
km.fit(X_scaled_minmax )
km_pred = km.fit_predict(X_scaled_minmax )
km_pred


array([0, 1, 1, 1, 2, 0, 2, 1, 1, 0, 0, 1, 2, 2, 2], dtype=int32)

In [428]:
df["Cluster"]= km_pred
df

Age   Sex  Monthly Income   Marital status  Service plan  Extra useage  \
0     54    0             3000               1           100             0   
1     59    0             4000               0           600            54   
2     38    1             7800               0           200            31   
3     18    0             8500               0           600           311   
4     27    1            14000               1           100           211   
5     29    0            31000               1          1600            25   
6     17    1             7500               0           600           254   
7     22    0             7900               0           200            31   
8     34    1            24700               0           100             7   
9     46    0            31110               1           600             0   
10    39    0            21000               1           800            64   
11    35    0            30000               0          1600             0   
12    39    1            40500               1          1600            50   
13    18    1             7800               0          1000           290   
14    22    1            18000               1           400           303   

    Cluster  
0         0  
1         1  
2         1  
3         1  
4         2  
5         0  
6         2  
7         1  
8         1  
9         0  
10        0  
11        1  
12        2  
13        2  
14        2

In [429]:
df = df.sort_values(["Cluster"])
df


Age   Sex  Monthly Income   Marital status  Service plan  Extra useage  \
0     54    0             3000               1           100             0   
5     29    0            31000               1          1600            25   
9     46    0            31110               1           600             0   
10    39    0            21000               1           800            64   
1     59    0             4000               0           600            54   
2     38    1             7800               0           200            31   
3     18    0             8500               0           600           311   
7     22    0             7900               0           200            31   
8     34    1            24700               0           100             7   
11    35    0            30000               0          1600             0   
4     27    1            14000               1           100           211   
6     17    1             7500               0           600           254   
12    39    1            40500               1          1600            50   
13    18    1             7800               0          1000           290   
14    22    1            18000               1           400           303   

    Cluster  
0         0  
5         0  
9         0  
10        0  
1         1  
2         1  
3         1  
7         1  
8         1  
11        1  
4         2  
6         2  
12        2  
13        2  
14        2